### ISSUE TITLE
How can I get credentials for authentication for the kubernetes/client-node library?

### ISSUE THREAD

**Issue by chrissound** [googleapis/nodejs-cloud-container#213]
Don't see anything at https://googleapis.dev/nodejs/container/latest/index.html#reference for auth / credentials.

I'm essentially looking for what `gcloud container clusters get-credentials standard-cluster-1   --zone us-central1-a` woud be doing. But instead for the client API. `kubernetes/client-node`.

**Comment by bcoe** [comment]
@chrissound if you're running on GKE, you should be able to specify a default service account to apply to containers that are provisioned. In turn, when you instantiate a library such as `nodejs-cloud-container`, it will use these default service credentials (which are automatically associated with the container). It does so using [google-auth-library-nodejs](https://github.com/googleapis/google-auth-library-nodejs#compute) under the hood.

**Comment by chrissound** [comment]
Yeah authentication is fine, but how do I get the k8s credentials/contexts?

I mean this is essentially what I came up with, but I basically gave up...
```
const k8s = require('@kubernetes/client-node');
const yaml = require('js-yaml');
const fs   = require('fs');
const { spawn } = require('child_process');
const { auth, Cluster } = require('google-auth-library');
const {google} = require('googleapis');
const container = require('@google-cloud/container');


exports.createJob = async function(){

    try {

        // const authClient = await auth.getClient({
            // scopes: [
                // 'https://www.googleapis.com/auth/cloud-platform',
            // ],
        // });
// 
        const client = new container.v1.ClusterManagerClient();

        const zone = 'us-central1-a';
        const projectId = await client.getProjectId();
        const clusterId = "standard-cluster-1";
        const request = {
          projectId: projectId,
          zone: zone,
          clusterId: clusterId
        };

        const response = await client.getCluster(request);

        const kc = new k8s.KubeConfig();
        kc.loadFromOptions({clusters: [response]});
        console.log(kc.getContexts());

        const k8sApi = kc.makeApiClient(k8s.BatchV1Api);
    } catch (e) {
        console.log(e);
        process.exit(1);
    }
}
```

**Comment by acasademont** [comment]
@chrissound did you manage to find more info? I'm interested in executing a command on a pod (kubectl exec) and I can't seem to connect both this library and the k8s client api for proper authentication :(

**Comment by chrissound** [comment]
I think this might help (warning - it's very confusing): https://googleapis.dev/nodejs/container/latest/google.container.v1.html#.GetClusterRequest

But yeah I don't think I found a solution.

I even brought it up 6 month ago on twitter: https://twitter.com/chrisczynski/status/1149668985752784897

**Comment by acasademont** [comment]
Thx!! We'll take a look

**Comment by kkorada** [comment]
is there any API to get admin credentials from cluster ?

**Comment by kriston13** [comment]
I'm still looking for an answer on this too.

This is where I got up to

```
// get the cluster information based on my existing application default credentials
        const [clusterResponse] = await gcpClient.getCluster(clusterProp);
        console.log(clusterResponse)

//recreate the structure of the `~/.kube/config` file in objects
        cluster = {
            name: `gke_${projectId}_${zone}_${clusterId}`,
            server: `https://${clusterResponse.endpoint}`,
            skipTLSVerify: true,
            caData: clusterResponse.masterAuth.clusterCaCertificate
        }
// this pulls the master username and password -> turns out this is NOT useful...
        user = {
            name: clusterResponse.masterAuth.username,
            password: clusterResponse.masterAuth.password
        }
        context = {
            name: 'my-context',
            user: user.name,
            cluster: cluster.name
        }

//then use the actual kube client
        const kc = new k8s.KubeConfig()
//this is the mocked up `~/.kube/config` setup
        kc.loadFromOptions({
            clusters: [cluster],
            users: [user],
            contexts: [context],
            currentContext: context.name
        })
        const k8sApis = kc.makeApiClient(k8s.CoreV1Api);
        return k8sApis.listNamespacedPod('default').then((response) => {
            console.log(`pods are: ${JSON.stringify(response.body)}`)
        })
        .catch((err) => {
            console.error(`caught: ${err.message}`)
            console.error(err)
        })
```
Except this gives me a `403` because the user from the `masterAuth` is an anonymous system user that can't do anything...

So I'm STILL stuck on trying to figure out how to get credentials from gcp.

**Comment by AlexeyAltunin** [comment]
@chrissound found a solution:

```
  const request = { projectId, zone, clusterId: clusterName };
  const cluster = (await client.getCluster(request))[0];
  const kc = new k8s.KubeConfig();

  kc.loadFromClusterAndUser(
    {
      name: cluster.name,
      server: `https://${cluster.endpoint}`,
      skipTLSVerify: true
    },
    {
      username: cluster.masterAuth.username,
      password: cluster.masterAuth.password
    }
  );
  const k8sApi = kc.makeApiClient(k8s.AppsV1Api);

  // find the particular deployment
  const res = await k8sApi.readNamespacedDeployment(name, namespace);
```

**Comment by gangchen03** [comment]
I ran into similar situation where I need to authenticate to GKE cluster externally from a GCE VM. Inspired by [this post](https://stackoverflow.com/questions/51838310/authentication-to-kubernetes-api-of-gke-cluster-within-google-cloud-function), I managed to get it working with the following code:

```
const k8s = require('@kubernetes/client-node');
const {GoogleAuth} = require('google-auth-library');

const clusterId = 'xxx-cluster';
const gke_zone = 'us-central1-a';

// This is google-auth-library application default authentication API
// It'll fetch the GCE service account automatically, we will use it for GKE credential
// Reference: https://github.com/googleapis/google-auth-library-nodejs#choosing-the-correct-credential-type-automatically 
const auth = new GoogleAuth({
    scopes: 'https://www.googleapis.com/auth/cloud-platform'
});

async function getPods(namespace) {
    const cluster = await configCluster(gke_zone, clusterId);
    /**
     * Automatically obtain application default credentials, and return
     * an access token for making requests.
     */
    const auth_token = await auth.getAccessToken();
    const k8s_client = new k8s.CoreV1Api('https://' + cluster.endpoint);

    // This method picks up GCP ADC to k8s context
    // It decorate API calls to GKE via  Oauth token
    k8s_client.setDefaultAuthentication({
        applyToRequest: (opts) => {
            // this is forming the certificate-authority for the api server
            opts.ca = Buffer.from(cluster.masterAuth.clusterCaCertificate, 'base64');
            if (!opts.headers) {
                opts.headers = [];
            }
            opts.headers.Authorization = 'Bearer ' + auth_token;
        },
    });

    k8s_client.listNamespacedPod('default').then((res) => {
	   console.log(res.body);
        },
        (err) => {
            console.log('Error!: ' + err);
        },
    );
}

/**
 * This method is equivalent of 
 * gcloud container clusters get-credentials cluster1 --zone us-central1-a --project project1
 */
async function configCluster(zone, clusterId) {

    /**
     * Instead of specifying the type of client you'd like to use (JWT, OAuth2, etc)
     * this library will automatically choose the right client based on the environment.
     */
    const client = await auth.getClient();

    const projectId = "project-xxx";
    const res = await client.request({
        url: `https://container.googleapis.com/v1/projects/${projectId}/zones/${zone}/clusters/${clusterId}`,
    });
    return res.data;
}

getPods('default').catch(console.error);
```
I have the GCE VM service account configured to access GKE cluster and integrated with GKE RBAC.

**Comment by JustinBeckwith** [comment]
@donmccasland a few folks have gotten tripped up here - sounds like a worthwhile thing to add to the docs on cloudsite!

**Comment by donmccasland** [comment]
agreed.  we'll start looking at a doc change.

**Comment by ggLuigi** [comment]
I tried with @gangchen03's method but failed with this error: 
```Error
{ HttpError: HTTP request failed
    at Request.localVarRequest [as _callback] (xxx/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:10042:40)
    at Request.self.callback (xxx/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (xxx/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (xxx/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
...
  response:
       IncomingMessage {
             ....
             body: 
             { kind: 'Status',
               apiVersion: 'v1',
               metadata: {},
               status: 'Failure',
               message:
                  'pods is forbidden: User "system:anonymous" cannot list resource "pods" in API group "" in the namespace "default"',
               reason: 'Forbidden',
               details: [Object],
               code: 403 
             } 
       },
   ...
}
```

I have tested the API via Postman with the same Bearer token, with the `https://${endpoint}/api/v1/namespaces/default/pods`, **without** enabling the "SSL certification verification", it successfully returns the correct response (showing all the pods).
So I tried with the same solution but added the `opts.strictSSL = false;` 
```
k8s_client.setDefaultAuthentication({
    applyToRequest: (opts => {
        opts.ca = Buffer.from(clusterCaCertificate, 'base64');
        if (!opts.headers) {
            opts.headers = [];
        }
        opts.headers.Authourization = 'Bearer ' + auth_token;
        opts.strictSSL = false;
    }),
});
```
Does anyone has any idea on this error? Would this be the permission setting of my GCP service account? (But it works via Postman Api call).

**Comment by Shabirmean** [comment]
The three essential components that are added to the kube-config file when `gcloud container clusters get-credentials ...` is called is:
1. The certificate authority data
2. The master node endpoint
3. The access token specific to the GCP service account that's used with the `gcloud` cli

The `gcloud` CLI tools updates the `kube/config` automatically to add a new context so that it can be used with the `kubectl` command subsequently. The following is a sample based off of what @gangchen03 has shared to get the same information as what's updated by `gcloud` when `get-credentials` is called. The example subsequently uses the `@kubernetes/client-node` library to list the services on the cluster

```js
const googleContainer = require('@google-cloud/container');
const k8s = require('@kubernetes/client-node');

// Create the Cluster Manager Client
const client = new googleContainer.v1.ClusterManagerClient();

/**
 * The following function is equivalent to the 'get-credentials' call using
 * gcloud. The client assumes that the 'GOOGLE_APPLICATION_CREDENTIALS'
 * environment variable is set to the json key file associated to your GCP
 * service account (https://cloud.google.com/docs/authentication/production#create_service_account).
 *
 * The return values of this method are the credentials that are used to update
 * the k8s config file (~/.kube/config) to add a new context when
 * 'get-credentials' is invoked by the 'gcloud' CLI
 */
async function getCredentials(cluster, zone) {
  const projectId = await client.getProjectId();
  const accessToken = await client.auth.getAccessToken();
  const request = {
    projectId: projectId,
    zone: zone,
    clusterId: cluster
  };

  const [response] = await client.getCluster(request);
  // the following are the parameters added when a new k8x context is created
  return {
    // the endpoint set as 'cluster.server'
    endpoint: response.endpoint,
    // the certificate set as 'cluster.certificate-authority-data'
    certificateAuthority: response.masterAuth.clusterCaCertificate,
    // the accessToken set as 'user.auth-provider.config.access-token'
    accessToken: accessToken
  }
}

async function listServices() {
  const k8sCredentials = await getCredentials('smean-cluster', 'us-central1-c');
  const k8s_client = new k8s.CoreV1Api('https://' + k8sCredentials.endpoint);
  /**
   * This method uses the same credentials that is stored in the k8s config file
   */
  k8s_client.setDefaultAuthentication({
    applyToRequest: (opts) => {
      opts.ca = Buffer.from(k8sCredentials.certificateAuthority, 'base64');
      if (!opts.headers) {
          opts.headers = [];
      }
      opts.headers.Authorization = 'Bearer ' + k8sCredentials.accessToken;
    },
  });

  k8s_client.listNamespacedService('default').then(
    (res) => {
      printServices(res.body.items);
    },
    (err) => {
      console.log('Error!: ' + err);
    },
  );
}

function printServices(services) {
  services.forEach(svc => {
    const name = svc.metadata.name;
    const type = svc.spec.type;
    const clusterIp = svc.spec.clusterIP;
    const externalIP = svc.spec.externalIPs || "<none>";
    let ports = "";
    svc.spec.ports.forEach((p) => ports += `${p.port}/${p.protocol},`)
    ports = ports || "<none>"
    console.log("" +
      name + "\t" +
      type + "\t" +
      clusterIp + "\t" +
      externalIP + "\t" +
      ports
    );
  });
}

listServices();
```

**Comment by Shabirmean** [comment]
@chrissound - You can also use the return values from `getCredentials()` above to build a `.kube/config` like configuration as follows and use the `@kubernetes/client-node` client methods.

_I have just re-written the `listServices()` method from the sample in [my earlier comment](https://github.com/googleapis/nodejs-cloud-container/issues/213#issuecomment-788369671)_
```js
async function listServices(cluster, zone) {
  const k8sCredentials = await getCredentials(cluster, zone);
  const k8sClientConfig = new k8s.KubeConfig();
  k8sClientConfig.loadFromOptions({
    clusters: [{
      name: `my-gke-cluster_${cluster}`,            // any name can be used here
      caData: k8sCredentials.certificateAuthority,  // <-- this is from getCredentials call
      server: `https://${k8sCredentials.endpoint}`, // <-- this is from getCredentials call
    }],
    users: [{
      name: `my-gke-cluster_${cluster}`,
      authProvider: 'gcp',                          // the is not a required field
      token: k8sCredentials.accessToken             // <-- this is from getCredentials call
    }],
    contexts: [{
      name: `my-gke-cluster_${cluster}`,
      user: `my-gke-cluster_${cluster}`,
      cluster: `my-gke-cluster_${cluster}`
    }],
    currentContext: `my-gke-cluster_${cluster}`,
  });
  const k8sApi = await k8sClientConfig.makeApiClient(k8s.CoreV1Api);
  k8sApi.listNamespacedService('default').then((res) => {
    printServices(res.body.items);
  });
}
```

Closing this issue, since the question is mostly specific to the usage of `@kubernetes/client-node` library with the k8s configuration returned by the `@google-cloud/container` library. Sufficient directions has been discussed. 

Please let us know if it's still required more clarification.

**Comment by u7min** [comment]
> 

Thank you
